# Generated by Django 4.2.7 on 2023-12-01 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='email_auth_token',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='verified_email',
        ),
    ]
