# Generated by Django 4.2.7 on 2023-12-01 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_useraccount_date_joined_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='user_type',
            field=models.CharField(choices=[('APPLICANT', 'Applicant'), ('STAFF', 'Staff'), ('COMMITTEE_MEMBER', 'Committee Member'), ('INSTRUCTOR', 'Instructor')], default='APPLICANT', max_length=50),
        ),
    ]
