# Generated by Django 4.2.7 on 2023-12-01 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_useraccount_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='full_name',
            field=models.CharField(default='John Doe', max_length=50),
            preserve_default=False,
        ),
    ]
